Task8
gudyrmik/qna pull request #7
Opened 2020-11-24 23:33 UTC by gudyrmik

2020-11-25 06:49 UTC, IvanShamatov requested changes

2020-11-25 06:49 UTC, IvanShamatov commented on app/controllers/answers_controller.rb
> +    @answer.save
create делает save. зачем тут еще раз save?

2020-11-25 06:49 UTC, IvanShamatov commented on app/models/link.rb
> +      GistService.new(gist_id).call
см примечания https://www.notion.so/ivanshamatov/gist-url-980ae83ea5fd464f8247f0de6ab052fb

2020-11-25 06:49 UTC, IvanShamatov commented on app/services/gist_service.rb
> +    Octokit::Client.new(:access_token => ENV['GITHUB_ACCESS_TOKEN'])
этот access_token -- он персональный (по всей видимости твой), а еще он истекает

2020-11-25 06:49 UTC, IvanShamatov commented on app/controllers/questions_controller.rb
> +                                      reward_attributes: [:title, :image]).merge!(user_id: current_user.id)
ты тут reward'у прописываешь текущего пользователя.
А следовательно до тех пор, пока пользователь не выберет какой-нибудь ответ верным, все награды будут отображаться у пользователя, создавшего вопрос на странице наград.

Очень удобно, создал сколько угодно вопросов с прикольными наградами и потом всем хвастаешься.

2020-11-25 06:49 UTC, IvanShamatov commented on spec/controllers/rewards_controller_spec.rb
> +
если не писать спеки, то они и падать не будут )

2020-11-25 06:49 UTC, IvanShamatov commented on spec/factories/rewards.rb
> +
по всей видимости эта фабрика тебе нигде не пригодилась

2020-11-25 06:49 UTC, IvanShamatov commented on spec/models/link_spec.rb
> +  it { should allow_value("https://pornhub.com").for(:url) }
👍

2020-11-25 22:38 UTC, gudyrmik commented on app/controllers/answers_controller.rb
> +    @answer.save
для надежности)

2020-11-26 06:57 UTC, IvanShamatov approved these changes

2020-11-26 06:57 UTC, IvanShamatov commented on app/controllers/questions_controller.rb
> +                                      reward_attributes: [:title, :image]).merge!(user_id: current_user.id)
я слепой, скобки просчитал, сорян, тут без претензий

2020-11-26 06:57 UTC, IvanShamatov commented on app/models/link.rb
> +    url.match(/https:\/\/gist.github.com\/\w+\/(\w+)/)[1] rescue nil
по возможности избегай использование `rescue nil`, это неочевидное поведение, 
```
if res = url.match(/https:\/\/gist.github.com\/\w+\/(\w+)/)
  res[0]
end
```
так на 2 строчки дольше, но зато не использует эксепшены для управления потоком программы

2020-11-26 06:57 UTC, IvanShamatov commented on config/application.rb
> +    config.before_configuration do
https://mkdev.me/posts/peremennye-okruzheniya-v-rails-dotenv-figaro-i-prochie
рекомендую либо dotenv гем использовать, либо figaro, где описание происходит в yaml формате. 

Если же ты хочешь придерживаться этой логики, то её нужно поместить в отдельный файл в папке initializers, application.rb не лучшее для этого место

2020-11-27 22:33 UTC, merged